# 数据增强参数：
lr0: 0.0001  # initial learning rate (SGD=1E-2, Adam=1E-3) 初始学习率 lr0 = 0.0001
lrf: 0.01  # final OneCycleLR learning rate (lr0 * lrf) 最终学习率 = 0.0001*0.01 = 1e-6

momentum: 0.937  # SGD momentum/Adam beta1
weight_decay: 0.0005  # optimizer weight decay 5e-4 正则化系数，过拟合的时候改大一点 * 10

warmup_epochs: 0.0  # warmup epochs (fractions ok)
warmup_momentum: 0.8  # warmup initial momentum
warmup_bias_lr: 0.1  # warmup initial bias lr

# 损失系数调节 0.05 box + 0.5 cls(1.0正+1.0负) + 1.0 obj(1.0正+1.0负)

# 最多+1%

box: 0.5  # box loss gain CIOU位置损失，占比 位置损失不收敛，可以调大一些 0.5
cls: 0.5  # cls loss gain 类别损占比 类别误检的时候调大1.5

cls_pw: 1.0  # cls BCELoss positive_weight 正样本类别损失占比 nn.BCEWithLogitsLoss(pos_weight=1.0)，漏检和误检1.5

obj: 1.0  # obj loss gain (scale with pixels) 置信度损失占比  漏检
obj_pw: 1.0  # obj BCELoss positive_weight  置信度正样本类别损失占比 nn.BCEWithLogitsLoss(pos_weight=1.0)，漏检1.5

iou_t: 0.20  # IoU training threshold 此项无用。源码里注释掉了此项

anchor_t: 4.0  # anchor-multiple threshold 不修改

# anchors: 3  # anchors per output layer (0 to ignore)
# 数据不平衡和难分样本的关注度
# fl_gamma = 1.5, 2.0  锦上添花功能
# alpha = 0.25
# 第1轮训练， epoch = 100, 92分的时候
# 第2轮训练时，再加focal loss才有效
fl_gamma: 1.5  # focal loss gamma (efficientDet default gamma=1.5) focal loss系数，此项有用。面试常问
fl_alpha: 0.25  # focal loss 正样本权重
iou_type: siou  # 边界框损失，可选 ciou 或 siou

hsv_h: 0.005  # image HSV-Hue augmentation (fraction)
hsv_s: 0.2  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.15  # image HSV-Value augmentation (fraction)
degrees: 0  # image rotation (+/- deg) 这里一般15
translate: 0.05  # image translation (+/- fraction)
scale: 0.5  # image scale (+/- gain) 缩放0.5
shear: 0.0  # image shear (+/- deg) 裁剪
perspective: 0.0  # image perspective (+/- fraction), range 0-0.001 不能设，透视变换
flipud: 0.5  # image flip up-down (probability) 上下翻转
fliplr: 0.5  # image flip left-right (probability) 左右翻转
mosaic: 0.2  # image mosaic (probability)
mixup: 0.0  # image mixup (probability)
copy_paste: 0.0  # segment copy-paste (probability) 此项只在分割有效
